### ISSUE TITLE
crashes on Sierra

### ISSUE THREAD

**Issue by tessus** [ElDeveloper/macfusion2#23]
I've opened this issue to combine the crash information mentioned in #11.

@artua [macfusionAgent_2016-10-03-230752_Artuas-iMac.crash.txt](https://github.com/ElDeveloper/macfusion2/files/507135/macfusionAgent_2016-10-03-230752_Artuas-iMac.crash.txt)

@gaelfoppolo 2.1.1-dev still crash at launch for me :/ ([report.txt](https://github.com/ElDeveloper/macfusion2/files/517571/report.txt))

@ExtRemo75 Same for me, 2.1.1-dev crashes at launch [report.txt](https://github.com/ElDeveloper/macfusion2/files/519491/report.txt) on Sierra 10.12

**Comment by existme** [comment]
Same for me

**Comment by ElDeveloper** [comment]
Would y'all mind testing this new release, it includes @166MMX's patch:

https://github.com/ElDeveloper/macfusion2/releases/tag/2.1.1-dev.2

**Comment by ExtRemo75** [comment]
@ElDeveloper Thank you, I have tested the 2.1.1-dev.2 but with the same result: crash. I've attached a new report below.

[report.txt](https://github.com/ElDeveloper/macfusion2/files/528745/report.txt)

**Comment by Bathtor** [comment]
Same for me. Report attached.
[report.txt](https://github.com/ElDeveloper/macfusion2/files/529233/report.txt)

**Comment by 166MMX** [comment]
I am sorry to hear that my attempt to fix that crash of @Bathtor, @ExtRemo75 and @gaelfoppolo failed so far.

Since this issue does relate to Login Items, it would be great to know what items you have in your Login Items list. Maybe even see (screenshot).
Is this the first time you try to run Macfusion on your system (fresh Install)?

Thing is that I have not been able to reproduce the crash on my own system so far. Could you please try [my debug build (Version 2.1.1-4932376e5f6bf3357bf6213356f0799c876f5a95)](https://infinit.io/_/6aMqhmP). It contains debug symbols and lacks compiler optimizations. Hopefully this will give us some hints to pin point the root cause of the issue.

--

The crash of @artua should be certainly fixed though.

**Comment by Bathtor** [comment]
Here is the report of the debug build: 
[report.txt](https://github.com/ElDeveloper/macfusion2/files/529765/report.txt)

Screenshot of login items:
<img width="429" alt="screen shot 2016-10-14 at 16 49 46" src="https://cloud.githubusercontent.com/assets/596721/19391782/4a2db93a-922e-11e6-9a36-af81638e0c88.png">

As you can see the MacFusion agent, which might be the old one (my system is not a fresh install). Maybe that is the problem?

**Comment by ExtRemo75** [comment]
Same here; I removed macfusionAgent from the login items which seems to fix the startup issue. Thank you!

**Comment by 166MMX** [comment]
@Bathtor Thanks for the screenshot and the report. Now I have been able to reproduce the crash by my own. Will send another pull request for it soon.

**Comment by artua** [comment]
Macfusion-2.1.1-dev.2 (no debug version) works for me. Thanks.
No Finder sidebar then mounted.

**Comment by ElDeveloper** [comment]
I've pushed a new pre-release here (with @166MMX's fix):

https://github.com/ElDeveloper/macfusion2/releases/tag/2.1.1-dev.3

**Comment by gaelfoppolo** [comment]
Macfusion-2.1.1-dev.3 works for me, with agent enabled 😃

**Comment by perfaram** [comment]
The fact of having the Android File Transfer agent (which is basically the official app for transferring data with a Android-running phone) also makes MacFusion crash on startup. Removing the AFT agent fixed it, so it's OK, but still I figured it would be better for everyone to know :)
